-- 021_drop_duplicate_indexes.sql
--
-- [2026-08-26] 완전히 겹치는 인덱스 5쌍에서 한쪽씩 제거한다.
--
-- 배경 (test_schema_hygiene.py 6-3, Sprint 100/121이 이미 세어 둔 것)
-- ---------------------------------------------------------------------------
-- 같은 컬럼 조합에 인덱스가 둘이면 **읽기 이득은 정확히 0이고** 쓰기 비용과 파일 크기만
-- 늘어난다. 이 저장소에서는 이름 규칙이 다른 두 계통이 서로를 모르고 각자 만들면서 생겼다
-- (`migrate_v4_1.py`의 `idx_ai_*` / `idx_*` vs 마이그레이션 008의 `idx_auction_item_*`).
--
-- Sprint 100은 이것을 세어 두고 **일부러 지우지 않았다** — 그때의 사유는
-- "현재 규모(1,876행/5.0MB)에서 API p95가 전부 3.1ms 이하라 병목이 없고,
--  인덱스 DROP은 스키마 변경이라 이득 없이 위험만 만든다" 였다. 그 판단은 그때 옳았다.
--
-- 무엇이 달라졌나 — **이득을 실제로 쟀다** (2026-08-26)
-- ---------------------------------------------------------------------------
-- 합성 500,000행 DB에서 이 5쌍만 제거하고 API가 실제로 쓰는 쿼리 9종을 전수 대조했다.
--
--     인덱스 생성        3,706ms -> 3,026ms   (18.4% 단축)
--     DB 파일 크기        333.4MB -> 298.5MB   (10.5%, 34.9MB 절감)
--     쿼리 계획 변화       9종 전부 SAME       (하나도 안 바뀐다)
--     쿼리 지연 변화       -2.3% ~ +3.9%       (전부 측정 잡음 범위)
--
-- 현재 규모(2,444행)에서도 INSERT 5,000행이 60.3ms -> 43.6ms 였다(다른 후보 포함 측정).
-- 즉 **읽기는 하나도 나빠지지 않고 쓰기와 용량만 좋아진다.** 계획이 전부 SAME인 이유는
-- 단순하다 — 남는 쪽이 지워지는 쪽과 **열 구성이 완전히 같아** 플래너가 대체재로 그냥 쓴다.
--
-- ★ 접두(prefix) 중복은 **일부러 손대지 않는다** — 지우면 느려진다
-- ---------------------------------------------------------------------------
-- 같은 측정에서 접두 중복(`idx_ai_sido` ⊂ `idx_auction_item_sido_sigungu` ⊂ `idx_search_main`,
-- `idx_auction_item_fail_count` ⊂ `idx_fail_count_date` 등)도 함께 지워 봤다. **크게 느려졌다.**
--
--     sido 검색        38.10ms ->  243.69ms   (+540%)   idx_ai_sido -> idx_search_main
--     COUNT(sido=?)     2.05ms ->    4.45ms   (+117%)
--     COUNT(fail>=?)    3.22ms ->    4.75ms   (+ 48%)
--
-- 이유는 **커버링 인덱스의 폭**이다. 좁은 인덱스는 엔트리가 작아 같은 범위를 훑어도 읽는
-- 페이지가 훨씬 적다. 넓은 인덱스로 대체하면 논리적으로는 같은 답이 나오지만 I/O가 는다.
-- "접두니까 중복"은 **점 조회에서만** 맞고 범위/커버링 스캔에서는 틀리다.
--
-- 2,444행에서는 이 차이가 안 보인다(sido 0.184ms -> 0.214ms). **작은 DB만 재고
-- 접두 인덱스를 지우면 규모가 커진 뒤에 5배 느려진다** — 이 주석은 그 함정을 남겨 둔다.
--
-- 어느 쪽을 남기는가 — **번호 마이그레이션이 만든 쪽**
-- ---------------------------------------------------------------------------
--     남긴다                              지운다                     지우는 쪽의 출처
--     idx_auction_item_auction_date       idx_ai_auction_date        migrate_v4_1.py + 013
--     idx_auction_item_case_no            idx_ai_case_no             migrate_v4_1.py + 013
--     idx_auction_item_minimum_bid_price  idx_minimum_bid_price      migrate_v4_1.py + 013
--     idx_rights_summary_item_id          idx_rs_item_id             migrate_v4_1.py
--     idx_audit_logs_admin                idx_audit_logs_admin_id    **출처 없음**(아래)
--
-- `idx_audit_logs_admin_id`는 저장소 어디에서도 만들지 않는다(전수 grep 0건). 즉 라이브
-- DB에 직접 만들어진 것이라 fresh clone에는 원래 없다 — 이 마이그레이션이 그 격차도 닫는다.
-- `test_bootstrap.py`의 알려진-격차 목록에서 이 항목을 함께 뺀다.
--
-- 안전성
-- ---------------------------------------------------------------------------
-- `DROP INDEX IF EXISTS`뿐이다. **테이블도 행도 건드리지 않는다** — 데이터 무손실이고
-- 재실행해도 안전하다. 되돌리려면 각 인덱스를 그대로 다시 CREATE 하면 되고, 그 SQL은
-- `008_create_search_indexes.sql` / `migrate_v4_1.py` / `013_*.sql`에 그대로 남아 있다.
--
-- ★ 013과 migrate_v4_1.py의 CREATE 문은 **그대로 둔다.** 이 파일이 그 뒤에 실행되므로
--   fresh bootstrap도 "만들었다가 지운다"로 같은 최종 상태에 도달한다. 이미 적용된
--   마이그레이션(013)을 나중에 고쳐 쓰는 것보다 이쪽이 안전하다.
--   다만 `migrate_v4_1.py`는 번호 마이그레이션이 아니라 **단독 재실행이 가능한**
--   부트스트랩 스크립트라, 거기서만 중복 CREATE 4줄을 함께 걷어낸다(재실행해도 되살아나지
--   않게). `idx_ai_sido`는 위 접두 사유로 **남긴다.**

DROP INDEX IF EXISTS idx_ai_auction_date;
DROP INDEX IF EXISTS idx_ai_case_no;
DROP INDEX IF EXISTS idx_minimum_bid_price;
DROP INDEX IF EXISTS idx_rs_item_id;
DROP INDEX IF EXISTS idx_audit_logs_admin_id;
