-- 027_drop_redundant_favorite_notes_index.sql
--
-- [2026-08-31 적용 / 2026-09-02 파일 복원] `favorite_notes` 의 접두 중복 인덱스를 지운다.
--
-- ★ 이 파일은 **복원본이다** — 원본이 없어졌다
-- ---------------------------------------------------------------------------
-- `migration_history` 에는 이 이름이 2026-08-31T03:00:02 에 적용됐다고 남아 있는데
-- (예약 실행 `run_daily.bat` 이 돌린 것), **디스크에도 git 이력 어디에도 파일이 없었다**
-- (`git log --all -- storage/migrations/027*` = 0건). 즉 DB 에 적용된 뒤 파일이
-- 커밋되지 않고 사라졌다. 028·029 도 같은 날 같은 식으로 사라졌다.
--
-- 그 결과 **저장소가 자기 DB 스키마를 재현하지 못했다.** 새로 clone 해서
-- init_db -> migrate_v4_1 -> run_migrations 를 돌리면 라이브에 없는 인덱스 3개가
-- 생겼다(실측 2026-09-02). `test_schema_hygiene.py` 3절이 이 방향을 잡아 붉어져 있었다.
--
-- 원본 SQL 을 볼 수 없으므로 **라이브 DB 에 남은 결과에서 역으로 복원했다.**
-- 파일명이 말하는 것과 라이브의 인덱스 목록이 정확히 일치한다:
--     라이브 favorite_notes 인덱스 = sqlite_autoindex_favorite_notes_1 뿐
--     026 이 만든 idx_favorite_notes_user_id 만 사라져 있다
--
-- 왜 지우는가 — 접두가 UNIQUE 자동 인덱스에 완전히 먹힌다
-- ---------------------------------------------------------------------------
-- `favorite_notes` 는 `UNIQUE(user_id, item_id)` 를 갖고, SQLite 는 그 제약에
-- `sqlite_autoindex_favorite_notes_1(user_id, item_id)` 를 자동으로 만든다.
-- 026 이 추가한 `idx_favorite_notes_user_id(user_id)` 는 그 **정확한 접두**다.
--
-- 021 이 남긴 경고("접두니까 중복은 점 조회에서만 맞다")를 그냥 넘기지 않고 다시 쟀다.
-- 이 표의 접근은 전부 `WHERE user_id = ?` / `WHERE user_id=? AND item_id=?` 점 조회다
-- (`api/v1/favorites.py`, `api/v1/favorite_import.py`). 021 이 문제 삼은 것은
-- auction_item 의 **범위·커버링 스캔**이었고 여기는 그 경우가 아니다.
--
-- 합성 100,000행 재측정 (2026-09-02, 사용자 4,000명 x 25행)
-- ---------------------------------------------------------------------------
--     notes 한 사용자   0.0089ms -> 0.0090ms  (+1.1%)   계획: 자동 인덱스로 대체
--     notes 단건        0.0010ms -> 0.0010ms  ( 0.0%)   계획 SAME
--     DB 파일           27.1MB   -> 22.4MB    (17.5% 절감, 029 와 합산)
--     20% 넘게 느려진 쿼리 0개
--
-- 즉 읽기는 그대로고 쓰기·용량만 좋아진다. 021 의 경고가 적용되지 않는 자리다.
--
-- 안전성 / 되돌리기
-- ---------------------------------------------------------------------------
-- `DROP INDEX IF EXISTS` 는 행을 건드리지 않는다. 되돌리려면 026 의 그 줄을 다시 만든다:
--     CREATE INDEX idx_favorite_notes_user_id ON favorite_notes(user_id);
-- 러너는 파일명으로 적용 여부를 판단하므로 라이브에서는 SKIP 되고, fresh 에서만 돈다.

DROP INDEX IF EXISTS idx_favorite_notes_user_id;
